name: dotnet build

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # - name: Setup .NET Core SDK
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: '5.0.x'
      # # - name: Install dependencies
      # #   run: dotnet restore --verbosity diagnostic
      # # - name: Install nuget dependencies
      # #   run: nuget restore Winditor.sln
      # - name: Build
      #   run: dotnet build --configuration Release --verbosity detailed
      # - name: Test
      #   run: dotnet test --no-restore --verbosity normal
      - name: Build
        run: msbuild /t:Build
